#lang pollen

◊`(main ([class "mx-auto"])
	  (section ([class "max-w-4xl mx-auto p-6 my-12 scroll-mt-20"])
		  (h2 ([class "text-4xl text-center mb-6"])
			  "Rechtliches")
		  (div ([class "flex flex-col items-start justify-around"])

		    (h3 ([class "my-3 text-xl"])
          "Impressum"
          (p ([class "max-w-3xl text-lg"])
            "Ev. Waldheim Spatzennest")
          (p ([class "max-w-3xl text-lg"])
            "Am Markt 7")
          (p ([class "max-w-3xl text-lg"])
            "72072 Tübingen")
          (p ([class "max-w-3xl text-lg"])
            "Tel: 07071 - 50 31")
          (p ([class "max-w-3xl text-lg"])
            "Fax: 07071 - 25 20 87")
          (p ([class "max-w-3xl text-lg"])
            "info.spatzennest-tuebingen@elkw.de")
          (p ([class "max-w-3xl text-lg"])
            "www.spatzennest-tuebingen.de")
        )
		    (h3 ([class "my-3 text-xl"])
          "Herausgeberin dieser Seite:"
          (p ([class "max-w-3xl text-lg"])
            "Waldheimleitung Frau Elke Schwendowius")
          (p ([class "max-w-3xl font-bold text-lg"])
            "Angaben gemäß § 5 TMG")
        )
		    (h3 ([class "my-3 text-xl"])
          "Verantwortliche für den Inhalt der Homepage nach § 55 Abs. 2 RStV:"
          (p ([class "max-w-3xl text-lg"])
            "Waldheimleitung")
          (p ([class "max-w-3xl text-lg"])
            "Elke Schwendowius")
          (p ([class "max-w-3xl text-lg"])
            "Email: info.spatzennest-tuebingen@elkw.de"))
		    (h3 ([class "my-3 text-xl"])
          "Haftungsausschluss: Inhalte"
          (p ([class "max-w-3xl text-lg"])
            "Unsere Inhalte sind sorgfältig recherchiert und erstellt. Dennoch können wir keinerlei Gewähr für die Aktualität, Korrektheit oder Vollständigkeit der bereitgestellten Informationen übernehmen. Haftungsansprüche gegen die oben aufgeführte Kirchengemeinde oder Einrichtung, welche sich auf Schäden materieller oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der dargebotenen Informationen bzw. durch die Nutzung fehlerhafter und unvollständiger Informationen verursacht wurden sind grundsätzlich ausgeschlossen, sofern seitens der Kirchengemeinde oder Einrichtung kein nachweislich vorsätzliches oder grob fahrlässiges Verschulden vorliegt. Alle Angebote sind freibleibend und unverbindlich. Die Kirchengemeinde oder Einrichtung behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen. ")
          )
		    (h3 ([class "my-3 text-xl"])
          "Verweise und Links"
          (p ([class "max-w-3xl text-lg"])
            "Die oben aufgeführte Kirchengemeinde oder Einrichtung ist nur für die eigenen Inhalte, also für diesen Internetauftritt, nach den allgemeinen Gesetzen verantwortlich.")
          (p ([class "max-w-3xl text-lg"])
            "Von diesen eigenen Inhalten sind Verweise (Links) zu anderen Webauftritten zu unterscheiden. Durch diese Links halten wir fremde Inhalte zur Nutzung bereit. Zum Zeitpunkt der Verlinkung haben wir den fremden Inhalt der verlinkten Seiten daraufhin überprüft, dass durch ihn keine mögliche zivilrechtliche oder strafrechtliche Verantwortlichkeit ausgelöst wird.")
          (p ([class "max-w-3xl text-lg"])
            "Wir können jedoch nicht ständig die Links auf unseren Seiten auf Veränderungen, die eine Verantwortlichkeit neu begründen könnten, kontrollieren. Wenn Sie den Eindruck haben, dass ein Link in unserem Webauftritt zu fremden Internetseiten mit rechtswidrigem oder strafrechtlichem Inhalt führt, geben Sie uns bitte Bescheid, damit wir diesen Link prüfen und gegebenenfalls entfernen können.")
          )
		    (h3 ([class "my-3 text-xl"])
          "Urheberrecht"
          (p ([class "max-w-3xl text-lg"])
            "Die oben aufgeführte Kirchengemeinde oder Einrichtung ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Grafiken, Tondokumente, Videosequenzen und Texte zu beachten, von ihr selbst erstellte Grafiken, Tondokumente, Videosequenzen und Texte zu nutzen oder auf lizenzfreie Grafiken, Tondokumente, Videosequenzen und Texte zurückzugreifen. Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind! Das Copyright für veröffentlichte, von der Kirchengemeinde oder Einrichtung selbst erstellte Objekte bleibt allein bei den Autoren der Seiten. Eine Vervielfältigung oder Verwendung solcher Grafiken, Tondokumente, Videosequenzen und Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung der oben aufgeführten Kirchengemeinde oder Einrichtung nicht gestattet. ")
          )
		    (h3 ([class "my-3 text-xl"])
          "Rechtswirksamkeit"
          (p ([class "max-w-3xl text-lg"])
            "Dieser Haftungsausschluss ist als Teil des Internetangebots zu betrachten, von dem aus auf diese Seite verwiesen wurde. Sofern Teile oder einzelne Formulierungen dieses Textes der geltenden Rechtslage nicht, nicht mehr oder nicht vollständig entsprechen sollten, bleiben die übrigen Teile des Dokuments in ihrem Inhalt und ihrer Gültigkeit hiervon unberührt.")
          )
      )))